# Generated by Django 5.0.2 on 2024-02-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auther_alter_post_auther'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auther',
            new_name='User',
        ),
    ]
