# Generated by Django 5.0.2 on 2024-02-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_auther_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='author',
        ),
    ]
